### ISSUE TITLE
make fails to build files

### ISSUE THREAD

**Issue by Sualannaigh** [giellalt/keyboard-yid#1]
Running make produces the following output:

```*** Building keyboards for the yid language. ***

CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh '/home/jacob/keyboard-yid/build-aux/missing' autoconf

*** macOS build! ***

  KBDGEN   mac
2024-11-21T12:05:22.947834Z  INFO kbdgen: kbdgen 3.0.0-beta.5
2024-11-21T12:05:22.948338Z  INFO kbdgen::bundle: Canonical Bundle Path: "/home/jacob/keyboard-yid/yid.kbdgen"
2024-11-21T12:05:22.961262Z  WARN kbdgen::bundle: Saw target with name win but did not parse
2024-11-21T12:05:22.961801Z  WARN kbdgen::bundle: Saw target with name mac but did not parse
thread 'main' panicked at src/bundle/resources/mod.rs:32:77:
called `Result::unwrap()` on an `Err` value: InvalidLanguage
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makefile:610: mac] Error 101
```

MacOS in particular does not seem to be the issue as it also fails to compile when running `make win` for instance.

**Comment by snomos** [comment]
The previous error disappeared after the file rename in the commit above, and the `win` build now continues to real errors.

The `mac` build still panics with this message:

```sh
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh '/Users/smo036/langtech/gut/giellalt/keyboard-yid/build-aux/missing' autoconf

*** macOS build! ***

  KBDGEN   mac
2024-11-22T17:11:46.715166Z  INFO kbdgen: kbdgen 3.0.0-beta.4
2024-11-22T17:11:46.715537Z  INFO kbdgen::bundle: Canonical Bundle Path: "/Users/smo036/langtech/gut/giellalt/keyboard-yid/yid.kbdgen"
2024-11-22T17:11:46.725332Z  WARN kbdgen::bundle: Saw target with name win but did not parse
2024-11-22T17:11:46.725348Z  WARN kbdgen::bundle: Saw target with name mac but did not parse
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/build/macos/macos_bundle.rs:50:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [mac] Error 101
```

But I am unable to identify what is causing the panic, or where the `None` value could be. Any clue, @dylanhand or @bbqsrc ?

**Comment by Sualannaigh** [comment]
Issue is now resolved with latest commit.
